function add(val){
    document.getElementById("display").value+=val;
}
function clearDisplay(){
    document.getElementById("display").value="";
}
function calculate(){
    document.getElementById("display").value=eval(document.getElementById("display").value)
}
var n=0;
function change(lesson, num){
    var chat= document.getElementById("chat_" + num);
    chat.innerHTML=lesson[n];
    if(n<lesson.length-1){
        n++;
    }
}
var l0=["Mmm… what—","I was sleeping, you see. But now—boing!—my eyes are open, and everything exists again all at once.","And that reminds me of something very important.", "Numbers.","Yes. I just woke up, and already I am thinking about numbers. This is because I am extremely intelligent.","Now, where was I… ah, yes. Numbers are how we understand how many things there are—like how many naps I have taken (many), or how many I will take (also many, but in the future, which is exciting).","Let us begin properly.", "You think numbers are just… things humans say when they count snacks. “One, two, three.” But no. Numbers are how we understand how many somethings exist. Like how many times I’ve tried to catch my tail today. (It’s a big number. Impressive, really.)","Let me explain.","When I have one ball of yarn, that means there is only a single, lonely, beautiful ball. Just one. I can stare at it. I can pounce on it. It is my entire universe.","But if I find two balls of yarn? Ah! Now things change. Two means more than one. It means choices. It means I can ignore one ball… and then immediately want the other one.","Then comes three. Three is exciting. Three is chaos. Three is when I try to chase all of them at once and fall over dramatically. Three means the world is getting bigger.","So numbers… they are names for “how many.” They help us keep track of things: toys, naps, snacks, and important life events, like how many naps I took only today.","(Also a big number. I am very productive.)","And the numbers don’t stop. They keep going forever. You can always add one more. Like… if I have four treats, and then I find another treat—because I will—now I have five. There is always more. Always another number waiting.","Numbers are like steps. Each one takes you further. From one… to two… to three… all the way to… well, as many as there are stars in the sky. Or crumbs under the couch.","So when you count, you are doing something very powerful. You are naming the size of the world.","Now if you’ll excuse me, I must go do something REALLY important, take a nap.","Zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"];
var l1=["Oh!! A treat!!","This is the best moment of my entire tiny kitten life. I must do math about it immediately.","Okay, okay—focus. Before, I had zero treats. Very sad number. But then—you gave me one. So now:","So now: Zero plus one equals… ONE TREAT!!","I am so happy I might zoom across the room. But wait, math is not finished.","Because now I have one treat. I can see it. I can smell it. I can—oh, I already ate it. That was fast. But it still counts in math!","So now I think… what if there is another? Just imagining. For learning purposes. Then:","One treat plus one treat equals TWO TREATS!!","Two treats means double happiness. Double purring. Double little tail wiggles. This is very important mathematical evidence","Addition is amazing. It means every time you give me something, I don’t lose the first one—I get more. The number grows, and my joy grows with it.","So right now, the official calculation is:","Me (one kitten) plus one treat equals one very happy kitten.","And if you add another treat… well… we can continue the lesson."];
var l2=["Mmm… what… where am I… oh. Oh! I’m awake.","I was having a very important dream about chasing… something. I don’t remember what. Probably math.","Okay. Hello. I am a slightly sleepy kitten, and today I will explain subtraction. But gently. Because I just woke up.","So… imagine this. Before my nap, I had three treats. I remember because I counted them very carefully: One… two… three. Yes. A good number. A comforting number.","Then… something happened.","I ate one.","Now we must do subtraction. Subtraction is when you take away something from what you had. Not as fun as addition. A little suspicious, honestly.","So we start with three treats… and we take away one treat…","Three minus one equals… two treats.","I checked. I looked at the floor. I looked in my paws. Only two left. The math is correct, even if I don’t like the result.","Sometimes subtraction just… happens. Like when a toy rolls under the couch: One toy… minus one lost toy… equals zero toys.","This is a tragedy. But also math.","Or when I had two naps planned… but I wake up early: Two naps… minus one unfinished nap… equals one nap.","This one is confusing and a little rude.","So subtraction means the number gets smaller. You start with some things, and then something is taken away, and now you have less. Less treats, less toys, less naps… I am not a big fan, but I understand it.","Anyway. I am awake now, which means: One sleepy kitten… minus one nap… equals one very awake kitten.","I think I need a treat to recover from this subtraction."];
var l3=["Oh—oh!! I just got a treat!!","Okay, this is serious. This is very important math time.","So I have one treat. Just one. I can see it. I can smell it. I love it. Life is perfect.","But then my tiny kitten brain has a BIG idea…","What if… instead of just adding treats one by one… we make groups of treats?","This is called multiplication. I think it means: “many treats at once,” which is clearly the best kind of math.","So look—if I have one treat, and then I get another treat, and another treat… that’s addition: One plus one plus one…","But multiplication says: “Why not just say it faster?”","So instead of saying: One treat + one treat + one treat…","We say: Three times one treat.","And that equals… THREE TREATS!!","Three! That is a pile. A small pile, but still a pile. I could sit in it. I could roll in it. I could eat it very quickly.","Or—wait—this is even better:","If I have two treats in each paw… (yes, I am imagining very carefully)… and I have two paws holding treats…","That’s: Two treats × two paws…","Equals… FOUR TREATS!!","This is not just math anymore. This is a lifestyle.","So multiplication is when you have groups of things, and you count all the groups at once. Instead of going slowly—one by one—you go BIG. You go FAST. You go MANY.","It’s like magic, but organized.","So right now: One kitten × one treat equals one happy kitten."];
var l4=["Huh…? Oh… I’m awake…","I was dreaming about a mountain of treats. A very important dream. But now I am here. And… wait…","There are treats.","Okay. I am awake enough for math.","So. I have… let me count… one, two, three, four treats. Four! A strong number. A comforting number. I like it.","But then… something strange happens.","I am not alone.","Peanut appears.","Now we must do division.","Division is when you take what you have… and you share it into equal parts. I am still deciding how I feel about this.","So we have four treats… and two kittens.","That means we split them. One for me… one for Peanut… one for me… one for Peanut…","So: Four treats ÷ two kittens = two treats each.","…okay. That is acceptable. I still have two. I can work with this.","But if there were more kittens…","Four treats ÷ four kittens…","That would be one treat each.","That feels… less exciting. Still fair. But less exciting.","And if there were too many kittens… Oh no.","This is why division must be handled carefully.","So division means taking a group and breaking it into equal smaller groups. Everyone gets the same amount. It is very fair. Suspiciously fair.","Now give me some treats. I think I need to recover from this division."];

